name: Build and Deploy
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    concurrency: 
      group: 'pages'
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install and Build 🔧
        
        run: |
          pnpm install --frozen-lockfile
          pnpm run build 
          cd dist
          cp index.html 404.html
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: production
          folder: dist
          path: './dist'